### PR TITLE
fix(handler files): move require block outside of handler for best lambda cold start performance

### LINKED ISSUE #77: Bizarre coldstart performance
I've encountered a rather odd performance bug. When using this plugin, some of my functions have a 7+ second coldstart time. When configuring iopipe manually coldstart time is less than 1 second. Subsequent non-coldstart invocations show no performance difference. Times are as reported by cloudwatch to eliminate any measurement difference that might occur due to different load points.

I've distilled the functions down to minimal projects to reproduce the issue. 

this is the code used with the plugin:
```
const google = require("googleapis").google;

exports.Test = async (event, context, callback) => {
  const mark = context.iopipe.mark;
  mark.start("start");
  const client = google.youtube({
    auth: process.env.YOUTUBE_API_KEY,
    version: "v3"
  });
  const res = await client.videos.list({
    id: "YjJ3uXxueeg",
    part: "snippet"
  });
  callback(null, {
    body: JSON.stringify(res.data),
    headers: {
      "Content-Type": "application/json"
    },
    statusCode: 200
  });
  mark.end("start");
}; 
```

and manually installed:
```
const google = require("googleapis").google;

const iopipe = require("@iopipe/iopipe")({
  token: process.env.IOPIPE_TOKEN
});

exports.Test = iopipe(async (event, context, callback) => {
  const mark = context.iopipe.mark;
  mark.start("start");
  const client = google.youtube({
    auth: process.env.YOUTUBE_API_KEY,
    version: "v3"
  });
  const res = await client.videos.list({
    id: "YjJ3uXxueeg",
    part: "snippet"
  });
  callback(null, {
    body: JSON.stringify(res.data),
    headers: {
      "Content-Type": "application/json"
    },
    statusCode: 200
  });
  mark.end("start");
});
```
[This is the complete project for the manual install.](https://github.com/iopipe/serverless-plugin-iopipe/files/2096542/iopipePerfManual.zip)

[This is the complete project using the plugin](https://github.com/iopipe/serverless-plugin-iopipe/files/2096545/iopipePerfPlugin.zip)

To test, you will need to put a iopipe token in config.yml. You will also need a Youtube api key. One can be generated using [these instructions](https://developers.google.com/youtube/v3/getting-started) or I can provide one over a more private communication method. 

Serverless Version: 1.27.3
@iopipe/iopipe: 1.7.0
serverless-plugin-iopipe: latest + #76

### PR DESCRIPTION
**Pull request by coreylight**
By moving the require block outside of the handler, AWS can properly use performance enhancements on their side to optimize the cold start.

fix #77

### CODE REVIEW

File: src/handlerCode.js [hunk 1]
```diff
@@ -1,7 +1,17 @@
+let handler, handlerError;
+try {
+  handler = require('../RELATIVE_PATH');
```
Comment (pselle) [inline src/handlerCode.js]: I can't remember understanding this before -- what's this `../RELATIVE_PATH` thing? Does it get replaced? a comment could be useful here. Unrelated to this change (the movement makes sense from the PR reasoning, although a comment about why it's here could be handy for source readers)

Comment (coreylight) [reply src/handlerCode.js]: Yes, this "code" actually gets imported as text with the capitalized pieces replaced. This is nice because we get syntax highlighting / formatting on this file but it doesn't have to be real / work.

**Comment by coreylight** [comment]
@kolanos the try/catch on `require` statements is the only mechanism to catch these types of errors that I know of. I'm not sure what kind of documentation you're looking for? We surface the error that is caught to IOpipe (as it does currently).

File: src/handlerCode.js (hunk 1 above)
Comment (pselle) [reply src/handlerCode.js]: It's out of the scope of this work, but that would be a really good comment if you don't mind bringing it in here (it's a little small to warrant an issue)
