### PR TITLE
Display source handler errors

### LINKED ISSUE #23: syntax errors in handler obscured - reports as iopipe-handler error
if my own handler has a syntax error I get:

```
Syntax error in module 'iopipe-handlers': SyntaxError
SyntaxError: Unexpected token )
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/iopipe-handlers.js:3:27)
```

The error in my own code is not logged.

### PR DESCRIPTION
**Pull request by coreylight**
Use `try / catch` to allow original errors (syntax or otherwise) to bubble to the top of the error stack.
- Fixes #23

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -291,8 +291,17 @@ class ServerlessIOpipePlugin {
     const iopipeInclude = `const iopipe = require('iopipe')({token: '${options()
       .token}'});`;
     const funcContents = _.chain(this.funcs)
-      .map(obj => {
-        return `exports['${obj.name}'] = iopipe(require('./${obj.relativePath}').${obj.method});`;
+      .map((obj, index) => {
+        return `exports['${obj.name}'] = function ${_.camelCase(
+          'attempt-' + obj.name
+        )}${index}(event, context, callback) {
+  try {
```
Comment (pselle) [inline src/index.js]: Did prettier OK this indentation?

File: src/index.js [hunk 2]
```diff
@@ -8,11 +8,26 @@ import options from './options';
...
+const handlerCode = fs.readFileSync(
+  join(__dirname, './handlerCode.js'),
+  'utf8'
+);
 
 function createDebugger(suffix) {
   return debugLib(`serverless-plugin-iopipe:${suffix}`);
 }
 
+function outputHandlerCode(obj = {}, index) {
```
Comment (pselle) [inline src/index.js]: Nice

File: src/index.js [hunk 3]
```diff
@@ -8,11 +8,26 @@ import options from './options';
...
+  const { name, relativePath, method } = obj;
+  const fnName = _.camelCase('attempt-' + name) + index;
+  return _.chain(handlerCode)
```
Comment (pselle) [inline src/index.js]: It it required to use _.chain here? It doesn't work without?
